when@dev: &dev
    zenstruck_foundry:
        make_factory:
            add_hints: false
            default_namespace: 'App\Tests\Factory'
        persistence:
            flush_once: true

    services:
        App\Tests\Factory\:
            resource: '%kernel.project_dir%/tests/Factory/'
            autowire: true
            autoconfigure: true
        App\Tests\Story\:
            resource: '%kernel.project_dir%/tests/Story/'
            autowire: true
            autoconfigure: true

when@test: *dev
