[supervisord]
nodaemon=true

[program:web]
command=php -S 0.0.0.0:8844 -t public
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord_web.log
stderr_logfile=/var/log/supervisord_web.err

[program:worker]
command=php bin/console messenger:consume async scheduler_sync_jellyfin --time-limit=3600
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisord_worker.log
stderr_logfile=/var/log/supervisord_worker.err
